"""add indexes to foreign keys

Revision ID: 383685c24d18
Revises: c81e6c2e4b86
Create Date: 2025-09-09 23:31:19.417713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383685c24d18'
down_revision = 'c81e6c2e4b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clean_records_documento_id'), ['documento_id'], unique=False)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_records_documento_id'), ['documento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_records_documento_id'))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_user_id'))

    with op.batch_alter_table('clean_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clean_records_documento_id'))

    # ### end Alembic commands ###
