"""add tamanho_kb and linhas to Documentos

Revision ID: b9e9601862f7
Revises: 383685c24d18
Create Date: 2025-09-09 23:35:10.631892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e9601862f7'
down_revision = '383685c24d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanho_kb', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('linhas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_column('linhas')
        batch_op.drop_column('tamanho_kb')

    # ### end Alembic commands ###
